baseURL = 'https://gavriliu.com'
languageCode = 'en-us'
title = 'Andrei Gavriliu'
DefaultContentLanguage = "en"

[menus]
[[menus.main]]
    name = "Home"
    url = ""
    weight = -3
[[menus.main]]
    name = "Projects"
    url = "projects/"
    weight = -2
[[menus.main]]
    name = "About"
    url = "about/"
    weight = -1
[[menus.social]]
    name = "github"
    type = "social"
    weight = 1
    url = "https://github.com/AndreiGavriliu"
[[menus.social]]
    name = "linkedin"
    weight = 2
    url = "https://www.linkedin.com/in/andreigavriliu/"
[[menus.social]]
    name = "xing"
    weight = 3
    url = "https://www.xing.com/profile/Andrei_Gavriliu"
[[menus.social]]
    name = "rss"
    weight = 4
    url = "index.xml"

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[pagination]
pagerSize = 10

[module]
[[module.imports]]
path = 'github.com/chipzoller/hugo-clarity'

[[module.imports]]
path = "github.com/hugomods/umami-analytics"