[[main]]
  name = "Home"
  url = ""
  weight = -110

# Submenus are done this way: parent -> identifier
# [[main]]
#   name = "Links"
#   identifier = "Links"
#   weight = -108
# [[main]]
#   parent = "Links"
#   name = "LinkedIn"
#   url = "https://www.linkedin.com/"
# [[main]]
#   parent = "Links"
#   name = "X"
#   url = "https://x.com/"

[[main]]
  name = "Projects"
  url = "projects/"
  weight = -107

# [[main]]
#   name = "About"
#   url = "about/"
#   weight = -107

# social menu links

[[social]]
  name = "github"
  type = "social"
  weight = 1
  url = "https://github.com/AndreiGavriliu"
[[social]]
  name = "linkedin"
  weight = 3
  url = "https://www.linkedin.com/in/andreigavriliu/"
[[social]]
  name = "xing"
  weight = 3
  url = "https://www.xing.com/profile/Andrei_Gavriliu"
[[social]]
  name = "rss"
  weight = 4
  url = "index.xml"