name: Tag Version

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  tag_version:
    if: github.event.pull_request.merged == true && startsWith(github.event.pull_request.head.ref, 'post-')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: "v"
          default_bump: "patch"
          release_branches: "main"
          fetch_all_tags: true

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          generate_release_notes: true